# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:  
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
              export SHIFTLEFT_ACCESS_TOKEN=${SHIFTLEFT_ACCESS_TOKEN}
              mvn -B -DskipTests clean package
              curl -O https://cdn.shiftleft.io/download/sl
              chmod a+x sl
              ./sl analyze --java --app TP-Java-Circle --wait --cpg target/tarpit-java.war
  
workflows:
  sample: 
    jobs:
      - build
