# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:  
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - store_artifacts:
          path: target/tarpit-java.war
  
  analyze:
    docker:
      - image: cimg/openjdk:8.0
    steps:
      - store_artifacts:
        path: target/tarpit-java.war
        destination: tarpit-java.war

      - run: |
        curl -O https://cdn.shiftleft.io/download/sl
        chmod a+x sl
        ./sl analyze ==java --app TP-Java-Circle --wait --cpg tarpit-java.war


workflows:
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - build
      - analyze
